  on: [push]
  name: Azure ARM
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        env:
          INPUT_SCOPE: subscription
          INPUT_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
          INPUT_TEMPLATE: https://raw.githubusercontent.com/Grevord/educational-teams-bot/features/arm_templates/arm_templates/arm_deploy_ressources.json
          INPUT_PARAMETERS: https://raw.githubusercontent.com/Grevord/educational-teams-bot/features/arm_templates/arm_templates/arm_deploy_ressources.parameters.dev.json ressources_base_name=qbot rgname=testdeploy rg_location=francecentral appName=qbot 
          INPUT_DEPLOYMENTNAME: test-deploy-dev
          
        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
